# This is the default pre-commit configuration file.
# It includes basic hygiene checks, security scans
# Pre-commit configuration file
# Documentation: https://pre-commit.com/
repos:
  # -------- Hygiene básica --------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1512"]

  # -------- Segurança: detect-secrets --------
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: '(^docs/.*$|^README\.md$|^internal/sockets/messagery/rabbitmq\.go$|^frontend/tsconfig\.json$|^docs/swagger\.json$|^frontend/src/locales/.*$)'
        files: '^(.*\.go$|.*\.yaml$|.*\.yml$|.*\.json$|.*\.tf$|.*\.tfvars$|.*\.sh$|.*\.ps1$)'
        pragma: allowlist dsn := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable", pgConfig.Username, pgConfig.Password, pgConfig.Host, port, pgConfig.Name)

  # -------- Segurança: semgrep --------
  # - repo: https://github.com/returntocorp/semgrep
  #   rev: v1.35.0
  #   hooks:
  #     - id: semgrep
  #       args:
  #         [
  #           "--config=auto",
  #           "--exclude=vendor/",
  #           "--exclude=docs/",
  #           "--exclude=support/",
  #         ]
  #       files: "^(.*\.go$|.*\.yaml$|.*\.yml$|.*\.json$|.*\.tf$|.*\.tfvars$|.*\.sh$|.*\.ps1$)"

  # -------- Segurança: bandit --------
  # - repo: https://github.com/PyCQA/bandit
  #   rev: v1.7.0
  #   hooks:
  #     - id: bandit
  #       args: ["-r", "."]

  # -------- Segurança: gitleaks --------
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks
        language: system
        pass_filenames: false
        args:
          [
            "protect",
            "--staged",
            "--no-banner",
            "--config=support/hooks/.gitleaks.toml",
          ]

  # -------- Go tools --------
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
#      - id: go-fmt
#      - id: go-vet
      - id: go-mod-tidy
        # - id: golangci-lint
        # args: ["run", "--config=support/hooks/.golangci.yaml"]
